### ISSUE TITLE
Missing Qualities

### ISSUE THREAD

**Issue by hofzinser** [superseva/ac2d20#2]
There are qualities we see in the GM guide like Bane. Can we get those added?

**Comment by superseva** [comment]
Definitely. I just need to get my hands on gm book ;). Can you oist missing ones here. Put X next to them if they are ranked

**Comment by hofzinser** [comment]
For your consideration.  Neither have levels
Qualities:
Hunger
Bane

**Comment by superseva** [comment]
These are weapon qualities, right ?

**Comment by hofzinser** [comment]
Correct - not damage effects

**Comment by superseva** [comment]
added in version 1.0.1
