### ISSUE TITLE
Suggestion: Calculate Bonus Damage on Range & Meele automaticly as calculate automaticly Armor

### ISSUE THREAD

**Issue by Ferigad** [superseva/ac2d20#27]
Hey, first of all, great project! I did allready some hours with my group on foundry, thanks to your project! =) So thanks for that.

But from my experience so far, we had several time the discussion if the bonus damage on meele and ranged has to been added manually (on the weapons you put in) or if the sheet does it automaticly: sadly, it doesnt do it automaticly.

Same are for armor that you can equip and unequip (couse you still have to put the extra armor manuelly in the front sheet). its not a must have feature but it would be a great quality of life feature, if it would be included.

Thanks again for that awesome system you did for foundry =)

**Comment by superseva** [comment]
Hi,
the sheet should automatically add the dmg bonus to the weapon damage rolls.
The Attribute/Bonus fields on the Character Sheet need to be filed
It should look something like this.

![chrome_28LEPzEIQe](https://user-images.githubusercontent.com/4093045/231241638-e8e7e30a-499e-4f7b-8439-20ed8a858557.png)

**Comment by Ferigad** [comment]
Ohhh okay, and i was puzzling allready what "Bonus" did mean in the context, now i get it, thanks! :D

**Comment by superseva** [comment]
There you go :)
