### ISSUE TITLE
Enhancement Request: Add Setting for Mouse Hover JSON file

### ISSUE THREAD

**Issue by theMagius0** [superseva/ac2d20#28]
Request to add a file path field in the A!C Settings so that a custom JSON file can be pointed to for Qualities, Damage Effects, etc.

(Note: this functionality would mimic what's currently in the Fallout 2d20 Settings.)

**Comment by superseva** [comment]
Done and done.
v10.0.9
Use the "system/ac2d20/assets/hovers.json" as the template to create your own
