### ISSUE TITLE
Ritual Magic

### ISSUE THREAD

**Issue by hofzinser** [superseva/ac2d20#3]
Wish list - it would be great to have a place on a Ritual spell to record breakthroughs (spell equivalent of injuries) and stress.  A place to record the effect for each breakthrough would be great. Look at the summon spell in Quick Trip to France for a template.

**Comment by superseva** [comment]
Added stress and steps. You still need to put the descriptions of effects, breakthroughs, miscasts, etc.  in the description field
v1.0.2
