### ISSUE TITLE
Talent compendium.

### ISSUE THREAD

**Issue by bluke** [superseva/ac2d20#7]
I have copied all the talents from the player's guide into a talent compendium. 
I seemed to work OK as part of a world, but I don't understand how I can test its integration to the system in a way that would work with a PR.

I'm joining the talents.db pack to this issue instead, in hope that it can be of use. [talents.zip](https://github.com/superseva/ac2d20/files/8307352/talents.zip)

**Comment by superseva** [comment]
Unfortunately we can’t include that since that material is considered copyrighted. There is no news about Modiphius considering the official release for the VTTs or changing their stance about distribution of files for Foundry.
